version: "3"

networks:
  laravel-network:
    driver: bridge

services:
  nginx:
    image: "nginx:stable-alpine"
    container_name: "nginx_laravel"
    ports:
      - "8088:80"
    volumes:
      - "./src:/var/www/html"
      - "./nginx:/etc/nginx/conf.d"
    depends_on:
      - php
      - mysql
    networks:
      - laravel-network
  mysql:
    image: "mysql:8.0"
    container_name: "mysql_laravel"
    ports:
      - "3308:3306"
    networks:
      - laravel-network
    volumes:
      - "./database:/data"
    environment:
      MYSQL_ROOT_PASSWORD: dominic1234.
      MYSQL_DATABASE: docker
      MYSQL_USER: dominic
      MYSQL_PASSWORD: dominic
  php:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: "php_laravel"
    ports:
      - "9000:9000"
    volumes:
      - "./src:/var/www/html"
    networks:
      - laravel-network

  composer:
    image: "composer:latest"
    container_name: "composer_laravel"
    volumes:
      - "./src:/var/www/html"
    working_dir: /var/www/html
    networks:
      - laravel-network
    tty: true

  npm:
    image: "node:13.7"
    container_name: "npm_laravel"
    volumes:
      - "./src:/var/www/html"
    working_dir: /var/www/html
    networks:
      - laravel-network
    tty: true

  redis:
    image: "redis:alpine"
    container_name: "redis_laravel"
    restart: unless-stopped
    tty: true
    ports:
      - "6380:6379"
    networks:
      - laravel-network
